# Generated by Django 2.0.6 on 2018-07-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='nombre',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
