# Generated by Django 2.0.6 on 2018-07-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='auto',
            name='categoria',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='home.Categoria'),
            preserve_default=False,
        ),
    ]
