# Generated by Django 2.0.6 on 2018-07-24 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180724_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concesionrio',
            new_name='Concesionario',
        ),
        migrations.AddField(
            model_name='auto',
            name='combustible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Combustible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='concesionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Concesionario'),
            preserve_default=False,
        ),
    ]
