# Generated by Django 2.0.6 on 2018-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180724_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='tipo',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina')], max_length=100),
        ),
    ]
