# Generated by Django 2.0.6 on 2018-08-22 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180814_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='concesionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Concesionario'),
        ),
    ]
