# Generated by Django 2.0.6 on 2018-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180821_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autos'),
        ),
    ]
