# Generated by Django 2.0.6 on 2018-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
    ]
