# Generated by Django 2.0.6 on 2018-08-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180828_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='marcas'),
        ),
    ]
